# -*- coding: utf-8 -*-
"""Email_automationCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3SEo-XMBa2VlwDqbz9TwrH5C56wgsaK

**Email automation code by Aniesh Das**
"""

import smtplib   #simple message transfer protocol to transfer reources from one server to another
import getpass   #function to get useres password & store and encrypt password. It is not echoed i.e doesnt show to programmer
from email.mime.text import MIMEText   #message contract that  contains all email information wrapped and shared with the google 

def send_email():
  sender_mail = 'anieshpictmun@gmail.com'
  password = getpass.getpass()
  #print(password)

  subject = 'Automated email sent through python script'
  msg = ''' Hello, this is to inform you that this email has been sent by a python bot automatically   
            - developed by Aniesh Das'''

  #server initialization
  server = smtplib.SMTP('smtp.gmail.com',587) #enables smtp protocol connection host name address:smtp.gmail.com port:587
  server.startttls()   #start server, tls handshake initiation
  server.login(sender_mail,password)   #share login details to server for login

  #draft my message 
  msg = MIMEText(msg)   #wraps all message info
  msg['Subject'] = subject
  msg['From'] = sender_mail
  msg['To'] = 'nextechprod7921@gmail.com'
  msg.set_param['importance','high value'] #sets importance paramter to email (optional)
  recipients = 'anieshpictmun@gmail.com , nextechprod7921@gmail.com , anieshpictmun@gmail.com'

  server.sendmail(sender_mail, recipients , msg.as_string())